### ISSUE TITLE
crash durante l'upload

### ISSUE THREAD

**Issue by SiNaPsEr0x** [c137ricksanchez/makerelease#23]
problema mentre sviluppavo una folder con piu file video

```
Avvio caricamento con ImgBly di: 00.10.00.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "***/automatic-releaser/venv/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "***automatic-releaser/gui.py", line 121, in make_release
    releaser.make_release()
  File "******automatic-releaser/src/makerelease/app.py", line 199, in make_release
    uploaded_imgs = [images.upload_to_imgur(img) for img in screenshots]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "******/automatic-releaser/src/makerelease/app.py", line 199, in <listcomp>
    uploaded_imgs = [images.upload_to_imgur(img) for img in screenshots]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*****automatic-releaser/src/makerelease/images.py", line 88, in upload_to_imgur
    return imgbly.upload_image(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*******/automatic-releaser/src/makerelease/api/imgbly.py", line 29, in upload_image
    full_url = f"{BASE_URL}ib/{full_res['data']['id']}.png"
                               ~~~~~~~~^^^^^^^^
KeyError: 'data'

```

**Comment by swadomlic** [comment]
anche io ho lo stesso problema, non funziona più

**Comment by SiNaPsEr0x** [comment]
me lo fa con alcuni formati piu grandi

**Comment by swadomlic** [comment]
io ho risolto disinstallando tutto compreso il python 3.12 e reistallando tutto
ora funziona perfetttamente

**Comment by SiNaPsEr0x** [comment]
Provo e in caso vi dico
